#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     testMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		if (nNxtButtonPressed == 2){
			motor[testMotor] = 50;
		}
		else if (nNxtButtonPressed == 1){
			motor[testMotor] = -50;
		}
		else if (nNxtButtonPressed == 3){
			int temp = nMotorEncoder[testMotor];
			if(nMotorEncoder[testMotor]<0){
				for(int i = temp; i<=0; i++){
					motor[testMotor]=100;
					nMotorEncoder[testMotor]=i;
				}
			} else if(nMotorEncoder[testMotor]>0){
				for(int i = temp; i>=0; i++){
					motor[testMotor]=100;
					nMotorEncoder[testMotor]=1;
				}
			}
		}
		else {
			motor[testMotor] = 0;
		}
		nxtDisplayBigTextLine(4, "%d", nMotorEncoder[testMotor]);
	}
}
