#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker600)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
int irs[5];

task main()
{
    HTIRS2readAllACStrength(IRSensor, irs[0], irs[1], irs[2], irs[3], irs[4]);

    writeDebugStreamLine("%d", "new line");
    writeDebugStreamLine("%d", irs[0]);
    writeDebugStreamLine("%d", irs[1]);
    writeDebugStreamLine("%d", irs[2]);
    writeDebugStreamLine("%d", irs[3]);
    writeDebugStreamLine("%d", irs[4]);
    wait1Msec(1000);
     /* nxtDisplaystring(2, irs[0]);
      nxtDisplaystring(3,  irs[1]);
      nxtDisplaystring(4,  irs[2]);
      nxtDisplaystring(5,  irs[3]);
      nxtDisplaystring(6,  irs[4]); */


}
