#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     testMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearDebugStream();

	motor[testMotor]=50;
	writeDebugStreamLine("Waiting... %d");
	wait1Msec(10000);

	for(int i=0;i<=100;i+=5){
		motor[testMotor] = i;
		writeDebugStreamLine("The motor value is: %d", i);
		wait1Msec(10000);
	}

	motor[testMotor] = 0;
	writeDebugStreamLine("Testing completed. %d");
}
